export enum ResearchStage {
    DATA_COLLECTION = 'DATA_COLLECTION',
    DATA_BALANCING = 'DATA_BALANCING',
    LABEL_ALIGNMENT = 'LABEL_ALIGNMENT',
    MODEL_EXPLORATION = 'MODEL_EXPLORATION',
    MODEL_REFINEMENT = 'MODEL_REFINEMENT'
}

export const STAGE_THRESHOLDS = {
    DATA_COLLECTION_MIN_RECORDS: 50,
    DATA_BALANCING_MAX_SHORTAGE: 5,
    LABEL_ALIGNMENT_MIN_AGREEMENT: 0.8
};
