
import { Finding, RiskLevel } from './types';

export const TONGUE_FINDINGS: Finding[] = [
  // ==========================================
  // 🚨 RED LEVEL: High Urgency / Medical Attention Needed
  // ==========================================
  {
    key: 'cyanosis',
    name: '青紫舌（チアノーゼ）',
    condition: '舌全体が青紫色 / 口唇も紫色',
    shortDescription: '血液中の酸素不足や重度の血行障害が疑われます。緊急性が高い状態です。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '直ちに救急受診または医療機関へ',
    reason: '呼吸循環機能の重大な低下を示唆するためです。',
    imageUrl: '/images/findings/cyanosis.png',
  },
  {
    key: 'leukoplakia',
    name: '白板症様所見',
    condition: '擦っても取れない厚い白斑 / 表面が硬い',
    shortDescription: '粘膜の異常な角化です。前がん病変の可能性があるため、専門的な確認が必要です。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '2週間以内に歯科・口腔外科へ',
    reason: '早期発見・早期対応が極めて重要なためです。',
    imageUrl: '/images/findings/leukoplakia.png',
  },
  {
    key: 'chronic_ulcer',
    name: '難治性潰瘍',
    condition: '2週間以上治らない口内炎 / 硬いしこり',
    shortDescription: '一般的な口内炎と異なり、長期間治らない潰瘍は詳しく調べる必要があります。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '歯科・口腔外科を受診',
    reason: '悪性腫瘍などの鑑別が必要なためです。',
    imageUrl: '/images/findings/ulcer.png',
  },
  {
    key: 'strawberry_tongue',
    name: 'イチゴ舌',
    condition: '鮮紅色で表面の粒々（乳頭）が強く隆起',
    shortDescription: '溶連菌感染症や川崎病などの特徴的な所見の可能性があります（特に小児）。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '発熱があれば内科・小児科へ',
    reason: '感染症や全身性炎症疾患の可能性があるためです。',
    imageUrl: '/images/findings/strawberry.png',
  },
  {
    key: 'deep_red_crimson',
    name: '絳舌（こうぜつ）',
    condition: '深紅〜暗赤色 / 乾燥していることが多い',
    shortDescription: '体内に極度の熱がこもっている、あるいは脱水が進んでいる状態を示します。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '水分補給・冷却・早めの内科受診',
    reason: '重度の炎症や脱水症状を示唆するためです。',
    imageUrl: '/images/findings/crimson.png',
  },
  {
    key: 'stiff_tongue',
    name: '強硬舌（きょうこうぜつ）',
    condition: '舌がこわばって動きにくい / 呂律が回らない',
    shortDescription: '脳血管障害（脳卒中など）の前兆や、熱による神経への影響が疑われます。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '呂律難や麻痺があれば直ちに救急へ',
    reason: '中枢神経系の障害を示唆する重要なサインです。',
    imageUrl: '/images/findings/stiff.png',
  },
  {
    key: 'deviated_tongue',
    name: '歪斜舌（わいしゃぜつ）',
    condition: '舌を出すと片側に曲がる',
    shortDescription: '脳卒中や顔面神経麻痺などの徴候の可能性があります。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '神経内科・脳神経外科を受診',
    reason: '神経系の異常による筋肉の麻痺を示唆するためです。',
    imageUrl: '/images/findings/deviated.png',
  },
  {
    key: 'short_tongue',
    name: '短縮舌（たんしゅくぜつ）',
    condition: '舌が縮んで短く、口の外に出しにくい',
    shortDescription: '重度の「寒」や極度の「熱」、または「気血」の著しい不足による危急のサインです。',
    riskLevel: RiskLevel.Red,
    recommendedAction: '医療機関で全身状態のチェックを',
    reason: '生命力の著しい低下や病状の進行を意味することがあるためです。',
    imageUrl: '/images/findings/short.png',
  },

  // ==========================================
  // ⚠️ YELLOW LEVEL: Caution / Lifestyle Improvement Needed
  // ==========================================

  // --- Tongue Color (Yellow Risk) ---
  {
    key: 'pale_tongue',
    name: '淡白舌（たんぱくぜつ）',
    condition: '色が薄く、白っぽい / 血色がない',
    shortDescription: '「気」や「血」が不足した、エネルギー不足・貧血気味の状態です。冷え性の方によく見られます。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '保温・栄養価の高い食事・十分な睡眠',
    reason: '代謝低下や免疫力低下につながるため、養生が必要です。',
    imageUrl: '/images/findings/pale.png',
  },
  {
    key: 'red_tongue',
    name: '紅舌（こうぜつ）',
    condition: '全体的に赤みが強い',
    shortDescription: '体内に熱がこもっている状態（実熱ないし虚熱）です。口の渇きやイライラを伴うことがあります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '香辛料やアルコールを控える・水分摂取',
    reason: '炎症傾向や自律神経の興奮状態を示唆します。',
    imageUrl: '/images/findings/red.png',
  },
  {
    key: 'purple_tongue',
    name: '紫舌（しぜつ）',
    condition: '全体的に青紫色や暗紫色',
    shortDescription: '血液循環が悪く、血が滞っている「瘀血（おけつ）」の状態です。慢性痛や冷えを伴うことが多いです。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '運動・温活・ストレス発散',
    reason: '血行不良は様々な慢性疾患の温床となるためです。',
    imageUrl: '/images/findings/purple.png',
  },
  {
    key: 'purple_spots',
    name: '瘀斑（おはん）・瘀点',
    condition: '舌に紫色のシミや点が見られる',
    shortDescription: '部分的な血行不良（瘀血）のサインです。肩こり、頭痛、生理不順と関連することがあります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '適度な運動・入浴・血流改善',
    reason: '慢性的な血行障害は様々な不調の原因となるためです。',
    imageUrl: '/images/findings/purple_spots.png',
  },

  // --- Tongue Shape/Texture (Yellow Risk) ---
  {
    key: 'swollen_tongue',
    name: '胖大舌（はんだいぜつ）',
    condition: '舌がむくんで大きく、口からはみ出しそう',
    shortDescription: '体内の水分代謝が低下し、余分な水分が溜まっている状態（水滞）です。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '水分の摂りすぎ注意・胃腸を休める・運動',
    reason: '消化機能の低下や慢性的疲労と関連するためです。',
    imageUrl: '/images/findings/swollen.png',
  },
  {
    key: 'teeth_marks',
    name: '歯痕舌（しこんぜつ）',
    condition: '舌の縁に歯型がついている / ギザギザしている',
    shortDescription: '舌がむくんでいるサインです。胃腸虚弱や慢性疲労、エネルギー不足の方によく見られます。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '消化の良い食事・休息・胃腸ケア',
    reason: '「気虚（エネルギー不足）」の代表的なサインだからです。',
    imageUrl: '/images/findings/teeth_marks.png',
  },
  {
    key: 'cracked_tongue',
    name: '裂紋舌（れつもんぜつ）',
    condition: '舌の表面に亀裂や溝がある',
    shortDescription: '体内の潤い（陰液）や血液が不足し、舌の組織が栄養されていない状態です。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '潤い補給・ビタミン摂取・夜更かしを避ける',
    reason: '慢性的な消耗状態や乾燥を示唆するためです。',
    imageUrl: '/images/findings/cracked.png',
  },
  {
    key: 'smooth_tongue',
    name: '鏡面舌（きょうめんぜつ）',
    condition: '表面がつるつるで苔がない / 光沢がある',
    shortDescription: '胃の気が極度に弱っている、または重度の栄養欠乏（ビタミンB12、鉄分等）の可能性があります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '内科での栄養相談・消化の良い食事',
    reason: '消化吸収機能の著しい低下や貧血の疑いがあるためです。',
    imageUrl: '/images/findings/smooth.png',
  },
  {
    key: 'prickles',
    name: '点刺（てんし）',
    condition: '赤い点状の隆起 / 表面がザラザラ',
    shortDescription: '熱や毒素が溜まっている、または強いストレスを感じているサインです。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: 'ストレス発散・睡眠・刺激物を控える',
    reason: '急性の炎症や精神的ストレスの蓄積を示すためです。',
    imageUrl: '/images/findings/prickles.png',
  },
  {
    key: 'flabby_tongue',
    name: '嫩舌（どんぜつ）',
    condition: '舌のきめが細かく、柔らかすぎる / 浮腫んでいる',
    shortDescription: '虚弱体質や、気血の不足を示します。疲れやすく、抵抗力が落ちている可能性があります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '十分な休養・栄養バランスの見直し',
    reason: '基礎体力の低下を示唆するため、養生が必要です。',
    imageUrl: '/images/findings/flabby.png',
  },

  // --- Tongue Coating (Yellow Risk) ---
  {
    key: 'thick_white_coating',
    name: '白厚苔（はくこうたい）',
    condition: '白い苔が分厚く付着している',
    shortDescription: '胃腸が冷えている、または食べ過ぎ・飲み過ぎで消化不良を起こしている可能性があります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '温かい飲食・腹八分目',
    reason: '「寒湿」や「食積」と呼ばれる停滞状態を示すためです。',
    imageUrl: '/images/findings/thick_coat.png',
  },
  {
    key: 'thick_yellow_coating',
    name: '黄厚苔（おうこうたい）',
    condition: '黄色く分厚い苔が付着している',
    shortDescription: '胃腸に熱がこもっている、または食べ過ぎによる「実熱」の状態です。口臭の原因にもなります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '野菜中心の食事・アルコールや脂質の制限',
    reason: '消化器系の炎症や過剰な熱を示すためです。',
    imageUrl: '/images/findings/thick_yellow.png',
  },
  {
    key: 'grey_black_coating',
    name: '黒苔・灰苔（こくたい）',
    condition: '灰色〜黒色の苔が付着している',
    shortDescription: '抗生物質の影響、喫煙、または極度の冷えや熱など、体のバランスが大きく崩れている可能性があります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '口腔ケア・原因薬の確認・禁煙',
    reason: '口腔内環境の著しい変化や、病状の進行・慢性化を示唆するためです。',
    imageUrl: '/images/findings/black_coat.png',
  },
  {
    key: 'greasy_coating',
    name: '膩苔（じたい）',
    condition: '油を塗ったようにベトベトした苔',
    shortDescription: '体内の湿気が過剰になり、老廃物が溜まっている「痰湿」の状態です。生活習慣病リスクの指標にもなります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '甘いもの・脂っこいものを控える・運動',
    reason: '代謝異常や体内のドロドロ状態を表すためです。',
    imageUrl: '/images/findings/greasy.png',
  },
  {
    key: 'dry_tongue',
    name: '燥舌（そうぜつ）',
    condition: '舌の表面や苔が乾燥している',
    shortDescription: '体内の水分（津液）が不足しているか、熱によって体液が消耗されています。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: 'こまめな水分補給・加湿・辛い物を控える',
    reason: '脱水傾向や陰液（体を潤す成分）の不足を示すためです。',
    imageUrl: '/images/findings/dry.png',
  },
  {
    key: 'peeled_coating_map',
    name: '剥落苔（はくらくたい）',
    condition: '苔が部分的に剥がれている',
    shortDescription: '胃腸の力が弱まり、気や陰液が部分的に不足しています。免疫力低下のサインの場合もあります。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '規則正しい食生活・無理のない生活',
    reason: '胃気や胃陰の不足を示すためです。',
    imageUrl: '/images/findings/geographic.png',
  },

  // --- Specific Areas (Yellow Risk) ---
  {
    key: 'red_tip',
    name: '舌尖紅（ぜっせんこう）',
    condition: '舌の先端だけが特に赤い',
    shortDescription: '「心火」のサイン。精神的なストレス、不眠、多夢などの症状と関連します。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: 'リラクゼーション・良質な睡眠',
    reason: '心身の過緊張状態を示唆するためです。',
    imageUrl: '/images/findings/red_tip.png',
  },
  {
    key: 'red_sides',
    name: '舌辺紅（ぜっぺんこう）',
    condition: '舌の両縁が赤い',
    shortDescription: '「肝火」のサイン。イライラ、怒りっぽい、目の疲れ、ホルモンバランスの乱れと関連します。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '休息・アロマ等でのリラックス・眼精疲労ケア',
    reason: '自律神経の乱れや高ぶりを示唆するためです。',
    imageUrl: '/images/findings/red_sides.png',
  },
  {
    key: 'sublingual_varices_severe',
    name: '舌下静脈怒張（強）',
    condition: '舌裏の静脈が太く黒っぽく浮き出ている',
    shortDescription: '強い血行不良（血瘀）のサインです。心臓血管系の負担や慢性的なコリを示唆します。',
    riskLevel: RiskLevel.Yellow,
    recommendedAction: '運動習慣・循環器系の検診検討',
    reason: '循環不全の一つの指標となるためです。',
    imageUrl: '/images/findings/sublingual_veins.png',
  },


  // ==========================================
  // ✅ GREEN LEVEL: Healthy / Benign / Normal Variations
  // ==========================================
  {
    key: 'normal_pink',
    name: '淡紅舌（たんこうぜつ）',
    condition: '適度な赤さ（薄いピンク）',
    shortDescription: '気血が充実し、循環も良好な健康的な舌の色です。',
    riskLevel: RiskLevel.Green,
    recommendedAction: '現在の良い生活習慣を継続しましょう',
    reason: '健康の指標となる理想的な状態です。',
    imageUrl: '/images/findings/normal.png',
  },
  {
    key: 'thin_white_coating',
    name: '薄白苔（はくはくたい）',
    condition: 'うっすらと白い苔が均一にある',
    shortDescription: '胃気があり、消化機能が正常に働いている証拠です。正常な苔の状態です。',
    riskLevel: RiskLevel.Green,
    recommendedAction: '健康的な状態です',
    reason: '苔が全くないよりも、うっすらあるのが理想的です。',
    imageUrl: '/images/findings/thin_white.png',
  },
  {
    key: 'geographic_tongue',
    name: '地図舌',
    condition: '赤い斑と白い縁取りが地図のように移動する',
    shortDescription: '一見驚きますが、体質的なもので良性であることが多いです。ストレスやビタミン不足で目立つことがあります。',
    riskLevel: RiskLevel.Green,
    recommendedAction: '痛みがないなら経過観察・刺激物を避ける',
    reason: '多くの場合、治療の必要がない良性状態だからです。',
    imageUrl: '/images/findings/geographic.png',
  },
  {
    key: 'sublingual_varices_mild',
    name: '軽度の舌下静脈',
    condition: '舌裏の静脈が見えるが、極端な怒張はない',
    shortDescription: '加齢とともに生理的に見えやすくなる変化です。病的な意味合いは低いです。',
    riskLevel: RiskLevel.Green,
    recommendedAction: '特になし（正常範囲）',
    reason: '加齢現象の一部であるためです。',
    imageUrl: '/images/findings/sublingual_mild.png',
  },
];
